########################################################################
# Toggle Cover
# To be used with a cover that only takes a toggle input.
# Endstops are required, and an optional obstacle sensor is supported.
# All inputs are active low, the output is used with an active low relay, and is on for a fixed duration to trigger the movement.
# The cover state is tracked using a template text sensor, which is updated based on the endstop inputs and the last command. This allows the cover to be used with Home Assistant's cover entity, which provides a lot of functionality for free (like assumed state, open/close/stop commands, etc).
##########################################################################
# Parameters:
# - move_delay: in ms The duration for the output to be on when triggering a movement. This should be long enough to reliably trigger the movement, but not too long to cause issues with the relay or the cover mechanism. Default is 1000ms.
# - move_pause: in ms The duration to wait after a movement command before allowing another command. This is to prevent sending multiple commands in quick succession, which could confuse the cover mechanism. Default is 1000ms.
# - light_delay: in ms The duration for the output to be on when triggering the light. Default is 500ms.

# - move_duration: Opening/Closing duration

# Pins
# - open_endstop_pin: The GPIO pin connected to the open endstop switch. This should be an active low switch that is closed when the cover is fully open.
# - closed_endstop_pin: The GPIO pin connected to the closed endstop switch. This should
# - sw_obstacle_sensor_pin: The GPIO pin connected to the obstacle sensor. This should be an active low sensor that is triggered when there is an obstacle in the way of the cover. This is optional, and can be enabled/disabled from Home Assistant using the "Obstacle Sensor Enabled" switch.


# Usage:

# esphome:
#   devices:
#   - id: door1_device
#     name: "Garage Door 1"
#   - id: door2_device
#     name: "Garage Door 2"
# packages:
#   # Door 1
#   door1: 
#     url: https://github.com/al3xius/esphome-toggle-cover
#     ref: main  # optional
#     refresh: 1s  # optional
#     files:
#       - path: toggle-cover.yaml
#         vars:
#           device_id: door1_device
#           move_duration: 1min
#           move_delay: 1000
#           move_pause: 1000
#           light_delay: 500

#           open_endstop_pin: 4
#           closed_endstop_pin: 18
#           obstacle_sensor_pin: 22
#           output_pin: 16

#   # Door 2
#   door2: 
#     url: https://github.com/al3xius/esphome-toggle-cover
#     ref: main  # optional
#     refresh: 1s  # optional
#     files:
#       - path: toggle-cover.yaml
#         vars:
#           device_id: door2_device
#           move_duration: 1min
#           move_delay: 1000
#           move_pause: 1000
#           light_delay: 500

#           open_endstop_pin: 19
#           closed_endstop_pin: 21
#           obstacle_sensor_pin: 23
#           output_pin: 17


##########################################################################

# ----- Defaults ------
defaults:
  move_delay: 1000
  move_pause: 1000
  light_delay: 500

binary_sensor:
  # Open Endstop
  - platform: gpio
    device_id: ${device_id}
    id: ${device_id}_sw_open
    name: "Limit Switch Open"
    entity_category: diagnostic
    pin:
      number: ${open_endstop_pin}
      mode:
        input: true
        pullup: true
    filters:
      - delayed_on_off: 10ms
    on_press:
      then:
        - lambda: |-
            id(${device_id}_state).publish_state("open");

  # Closed Endstop
  - platform: gpio
    device_id: ${device_id}
    id: ${device_id}_sw_closed
    name: "Limit Switch Closed"
    entity_category: diagnostic
    pin:
      number: ${closed_endstop_pin}
      mode:
        input: true
        pullup: true
    filters:
      - delayed_on_off: 10ms
    on_press:
      then:
        - lambda: |-
            id(${device_id}_state).publish_state("closed");

  # Obstacle Sensor
  - platform: gpio
    device_id: ${device_id}
    id: ${device_id}_obstacle_detected
    name: "Obstacle"
    device_class: motion
    entity_category: diagnostic
    pin:
      number: ${obstacle_sensor_pin}
      mode:
        input: true
        pullup: true
    filters:
      - delayed_on_off: 10ms

  
  # High State Confidence
  - platform: template
    device_id: ${device_id}
    id: ${device_id}_high_state_confidence
    name: "High State Confidence"
    lambda: |-
      return id(${device_id}_state).state == "open" || id(${device_id}_state).state == "closed" || id(${device_id}_previous_state).state == "open" || id(${device_id}_previous_state).state == "closed";


  # Obstacle State for closing (combines the obstacle sensor with the enabled state from the config switch)
  - platform: template
    device_id: ${device_id}
    id: ${device_id}_obstacle_active
    device_class: problem
    lambda: |-
      if (!id(${device_id}_obstacle_enabled)) {
        return false;
      }
      return id(${device_id}_obstacle_detected).state;

  # Obstacle State for Opening (only prevent opening if the obstacle sensor is triggered, and the door is not fully closed). This is needed to prevent accidentally closing if the actual state desyncs from the assumed state.
  - platform: template
    device_id: ${device_id}
    id: ${device_id}_obstacle_active_opening
    device_class: problem
    lambda: |-
      if (!id(${device_id}_obstacle_enabled)) {
        return false;
      }
      return id(${device_id}_obstacle_detected).state && !id(${device_id}_high_state_confidence).state;

  # Endstop Error (both endstops active at the same time, which should be impossible and indicates a wiring or hardware issue)
  - platform: template
    device_id: ${device_id}
    id: ${device_id}_endstop_error
    name: "Endstop Error"
    device_class: problem
    entity_category: diagnostic
    lambda: |-
      return id(${device_id}_sw_open).state && id(${device_id}_sw_closed).state;

switch:
  # Relay Output
  - platform: gpio
    id: ${device_id}_output
    device_id: ${device_id}
    inverted: True
    pin:
      number: ${output_pin}
      mode:
        output: true
        open_drain: true

  # Obstacle Sensor Enable Switch (used to enable/disable the obstacle sensor from the config, which can be useful for testing or if the sensor is not working properly)
  - platform: template
    device_id: ${device_id}
    id: ${device_id}_obstacle_enable_switch
    name: "Obstacle Sensor Enabled"
    optimistic: true
    entity_category: config
    restore_mode: RESTORE_DEFAULT_ON
    lambda: |-
      return id(${device_id}_obstacle_enabled);
    turn_on_action:
      - globals.set:
          id: ${device_id}_obstacle_enabled
          value: "true"
    turn_off_action:
      - globals.set:
          id: ${device_id}_obstacle_enabled
          value: "false"

button:
  # Turn on Light
  - platform: template
    device_id: ${device_id}
    id: ${device_id}_light
    name: "Door 1 Light"
    icon: "mdi:lightbulb"
    on_press:
      - switch.turn_on: ${device_id}_output
      - delay: ${light_delay}ms
      - switch.turn_off: ${device_id}_output

  # Toggle Movement
  - platform: template
    device_id: ${device_id}
    id: ${device_id}_toggle
    icon: "mdi:swap-vertical"
    on_press:
      - if:
          condition:
            binary_sensor.is_off: ${device_id}_endstop_error
          then:
            - switch.turn_on: ${device_id}_output
            - delay: ${move_delay}ms
            - switch.turn_off: ${device_id}_output
          else:
            - logger.log: "Door 1 endstop error active, refusing movement"

  # switch direction
  - platform: template
    id: ${device_id}_toggle_2
    on_press:
      - button.press: ${device_id}_toggle
      - delay: ${move_pause + move_delay}ms
      - button.press: ${device_id}_toggle

  # continue in the same direction
  - platform: template
    id: ${device_id}_toggle_3
    on_press:
      - button.press: ${device_id}_toggle
      - delay: ${move_pause + move_delay}ms
      - button.press: ${device_id}_toggle
      - delay: ${move_pause + move_delay}ms
      - button.press: ${device_id}_toggle

# ----- Basic Cover Logic -----
cover:
  - platform: feedback
    device_id: ${device_id}
    name: "Door"
    device_class: garage
    has_built_in_endstop: true
    direction_change_wait_time: 2s
    obstacle_rollback: 0

    open_action:
      - script.execute:
          id: ${device_id}_smart_move_script
          cmd: "open"
    open_duration: ${move_duration}
    open_endstop: ${device_id}_sw_open
    open_obstacle_sensor: ${device_id}_obstacle_active_opening

    close_action:
      - script.execute:
          id: ${device_id}_smart_move_script
          cmd: "close"
    close_duration: ${move_duration}
    close_endstop: ${device_id}_sw_closed
    close_obstacle_sensor: ${device_id}_obstacle_active

    stop_action:
      - script.execute:
          id: ${device_id}_smart_move_script
          cmd: "stop"

# ----- Handle Advanced Toggle Logic -----
script:
  - id: ${device_id}_smart_move_script
    parameters:
      cmd: string
    then:
      - lambda: |-
          auto open = id(${device_id}_sw_open).state;
          auto closed = id(${device_id}_sw_closed).state;
          auto state = id(${device_id}_state).state;
          id(${device_id}_previous_state).publish_state(state);

          // Error
          if (open && closed) {
            id(${device_id}_state).publish_state("error");
            return;
          }

          // Open
          if (cmd == "open") {
            // Starting from endstop
            if (closed || state == "closed") {
              id(${device_id}_toggle).press();
            }
            // Starting in the middle
            else if (state == "stopped_closing") {
              id(${device_id}_toggle).press();
            }
            else if (state == "stopped_opening") {
              id(${device_id}_toggle_3).press();
            }
            else if (state == "closing") {
              id(${device_id}_toggle_2).press();
            }
            else if (open) {
              return;
            }
            else {
              // fall back to normal toggle if state is unknown
              id(${device_id}_toggle).press();
            }

            id(${device_id}_state).publish_state("opening");
            return;
          }

          // Close
          if (cmd == "close") {
            // Starting from endstop
            if (open || state == "closed") {
              id(${device_id}_toggle).press();
            }
            // Starting in the middle
            else if (state == "stopped_opening") {
              id(${device_id}_toggle).press();
            }
            else if (state == "stopped_closing") {
              id(${device_id}_toggle_3).press();
            }
            else if (state == "opening") {
              id(${device_id}_toggle_2).press();
            }
            else if (closed) {
              return;
            }
            else {
              // fall back to normal toggle if state is unknown
              id(${device_id}_toggle).press();
            }

            id(${device_id}_state).publish_state("closing");
            return;
          }

          // Stop
          if (cmd == "stop") {
            if (open || closed) {
              return;
            }
            if (state == "stopped_opening" || state == "stopped_closing") {
              return;
            }
            // Stopping in the middle
            if (state == "opening") {
              id(${device_id}_toggle).press();
              id(${device_id}_state).publish_state("stopped_opening");
              return;
            }
            if (state == "closing") {
              id(${device_id}_toggle).press();
              id(${device_id}_state).publish_state("stopped_closing");
              return;
            }

            id(${device_id}_state).publish_state("error");
            return;
          }

text_sensor:
  # State Sensor (open/closed/opening/closing/stopped_opening/stopped_closing/error)
  - platform: template
    device_id: ${device_id}
    id: ${device_id}_state
    name: "State"

  - platform: template
    device_id: ${device_id}
    id: ${device_id}_previous_state
    name: "Previous State"

globals:
  # Obstacle Enabled Global (used to store the enabled state of the obstacle sensor, which can be controlled from the config switch and is used in the obstacle enabled binary sensor)
  - id: ${device_id}_obstacle_enabled
    type: bool
    restore_value: true
    initial_value: "true"
